### ISSUE TITLE
Constructors with string keys not working

### ISSUE THREAD

**Issue by alunap** [bkamins/JuliaCon2019-DataFrames-Tutorial#1]
I ran both 
julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'
and
julia --project=. -e 'using IJulia; notebook(dir=pwd())'
but a number of the first notebook cells fail to run. This is generally about constructors that use strings as column names. eg
DataFrame("A" => [1,2], "B" => [true, false], "C" => ['a', 'b'])
gives
MethodError: no method matching DataFrame(::Pair{String,Array{Int64,1}}, ::Pair{String,Array{Bool,1}}, ::Pair{String,Array{Char,1}})
Closest candidates are:
  DataFrame(::T; copycols) where T at /Users/alun/.julia/packages/DataFrames/S3ZFo/src/other/tables.jl:30

DataFrame(rand(3))
gives
ArgumentError: 'Array{Float64,1}' iterates 'Float64' values, which doesn't satisfy the Tables.jl `AbstractRow` interface

DataFrame([1:3, 4:6, 7:9], ["A", "B", "C"])
gives
MethodError: no method matching DataFrame(::Array{UnitRange{Int64},1}, ::Array{String,1})
Closest candidates are:
  DataFrame(::AbstractArray{var"#s36",1} where var"#s36"<:(AbstractArray{T,1} where T)) at /Users/alun/.julia/packages/DataFrames/S3ZFo/src/dataframe/dataframe.jl:186
  DataFrame(::AbstractArray{var"#s35",1} where var"#s35"<:(AbstractArray{T,1} where T), !Matched::AbstractArray{Symbol,1}; makeunique, copycols) at /Users/alun/.julia/packages/DataFrames/S3ZFo/src/dataframe/dataframe.jl:186
  DataFrame(::AbstractArray{T,1} where T, !Matched::AbstractArray{Symbol,1}; makeunique, copycols) at /Users/alun/.julia/packages/DataFrames/S3ZFo/src/dataframe/dataframe.jl:176

**Comment by bkamins** [comment]
Please make sure that you have downloaded the whole repository AND run the Jupyter Notebook from this directory.
You use DataFrames.jl version 0.20 and the tutorial is for 0.21 (and this is the version in Manifest.toml in the repository)
